const BASE_DAMAGE_DIVISOR = 50;
const BASE_LEVEL_DIVISOR = 5;
const BASE_DAMAGE_BONUS = 2;
const MIN_RANDOM_FACTOR = 0.85;
const MAX_RANDOM_FACTOR = 1.0;
const DEFAULT_LEVEL = 50;
const STAB_BONUS = 1.5;
const NO_STAB_BONUS = 1.0;
